[[headers]]
for = "/assets/css/*"
[headers.values]
Cache-Control = "max-age=86400, must-revalidate, public"

[[headers]]
for = "/assets/js/*"
[headers.values]
Cache-Control = "max-age=86400, must-revalidate, public"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "max-age=86400, must-revalidate, public"

[[headers]]
for = "/assets/css/images/*"
[headers.values]
Cache-Control = "max-age=86400, must-revalidate, public"

[[headers]]
for = "/assets/fonts/*"
[headers.values]
Cache-Control = "max-age=86400, must-revalidate, public"
